### ISSUE TITLE
QNN C++ Example Issue

### ISSUE THREAD

**Issue by hhschumann** [microsoft/onnxruntime-inference-examples#344]
Hi,

I am trying to the run the example for QNN using C++ and am getting an error stating that QNN execution provider is not supported with this build. I followed the build instructions for ORT for Arm64 with QNN support [here](https://onnxruntime.ai/docs/build/eps.html#windows-arm64-native-build) and am using a 2023 Windows Dev Kit. 

Thanks

**Comment by adrianlizarraga** [comment]
Hi @hhschumann 

Can you please provide the following information:
- Exact build command used to build onnxruntime
- The exact error message
- Confirmation that you are building on Windows ARM64

Thank you

**Comment by hschumanncvx** [comment]
- I followed the build instructions here: https://onnxruntime.ai/docs/build/eps.html#build-instructions-5
- Error messages was "QNN execution provider is not supported with this build"
- Correct, I am building on Windows ARM64

**Comment by HectorSVC** [comment]
We already have multiple people verified the example code without any problem.
You shouldn't get the error if you set the "--use_qnn --qnn_home [QNN_SDK path]" in your build command. I'm not sure what's wrong here.
Were you build on the 2023 Dev kit?
Could you provide the Onnxruntime build log?

**Comment by hschumanncvx** [comment]
@HectorSVC

I rebuilt Onnxruntime from the source and pulled in the latest version of the example and was able to get the example to work. There was still a minor issue with the ONNX model URL line 3 of run_qnn_ep_sample.bat. It gives me a 404 error. I was able to find the model at https://github.com/onnx/models/blob/main/validated/vision/classification/mobilenet/model/mobilenetv2-12.onnx but for some reason was getting the error "Failed to load model because protobuf parsing failed" when downloading it using the .bat script. However, when I manually downloaded the model and placed it in the example directory, it worked. Not sure why that issue occured.

**Comment by HectorSVC** [comment]
Oh, no, they moved the folder again. They did that several weeks ago by moving it to archive folder. I'll submit a PR to fix it.
The correct path should be https://github.com/onnx/models/**_raw_**/main/validated/vision/classification/mobilenet/model/mobilenetv2-12.onnx.
But anyway, good news from your side.
Can we close this issue now?

**Comment by HectorSVC** [comment]
https://github.com/microsoft/onnxruntime-inference-examples/pull/365

**Comment by hschumanncvx** [comment]
@HectorSVC yes you may close the issue. Thanks!
