### ISSUE TITLE
 The result of sample "mobilenetv2_classification" is unexcepted.

### ISSUE THREAD

**Issue by JohnnyWang19921007** [microsoft/onnxruntime-inference-examples#357]
[Issue]
When we try the sample "mobilenetv2_classification" with "Option 2: Use context binary generated by native QNN tool chain", the result is unexcepted.
We have tried:

1. Two formats of input, but the result is still wrong.
2. Using qnn tool to assign the input layout in dlc.

Suspect that the versions of onnxruntime and qnn sdk caused this issue.

Excepted:
![1cf83814e155b7271542d967720cb27](https://github.com/microsoft/onnxruntime-inference-examples/assets/23184292/da079e6f-1e60-4555-be27-defff7202989)
Result:
<img width="781" alt="image" src="https://github.com/microsoft/onnxruntime-inference-examples/assets/23184292/931da145-3956-45a7-937b-29d564a20f2a">

[Reproduce Steps]
We follow the steps of the "Option 2: Use context binary generated by native QNN tool chain" in https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/QNN_EP/mobilenetv2_classification
Here is the sample we built: https://1drv.ms/u/s!AvGtWauU4SjguzT0kHuBr2c7gXye?e=hyrofZ

[Environment]
- Processer: Snapdragon (TM) 8cx Gen 3
- onnxruntime : v1.16.3 with [PR 17757](https://github.com/microsoft/onnxruntime/pull/17757).
- qnn sdk : 2.17.0.231124

**Comment by HectorSVC** [comment]
It could be caused by the quantization. Ideally, it should cover as more data as possible. Here, we only used a single input file kitten.jpg to demonstrate the workflow.

I don't know the details regarding to your cls_qnn.exe. I did a trick with our existing example, that, put your goldfish.jpg into the images folder, rename it to kitten.jpg, and delete the kitten_input.raw & kitten_input_nhwc.raw. Then run our example again. It get the correct result for the first 2 runs.
position=1, classification=n01443537 goldfish, Carassius auratus, probability=28.157501

The last run got incorrect result also:
position=0, classification=n01440764 tench, Tinca tinca, probability=13.637315

That's because the QDQ model get re-quantized with new data sets (the golden fish image). However the context binary generated by native QNN tool chain was not changed, so the quantization parameter may not fit for the new data set. You can try to re-generate the QNN context binary using QNN tool chain with new data set. And run it again. It should resolve the issue.

**Comment by JohnnyWang19921007** [comment]
Thanks for the reply, we will check it detailly.

Before that we want to share further about our cls_qnn.exe.
It is referred to [Main.cpp](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/QNN_EP/mobilenetv2_classification/main.cpp) in the [mobilenetv2_classification](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/QNN_EP/mobilenetv2_classification) sample.
The only different think is compiling with the latest onnxruntime  v1.16.3 with [PR 17757](https://github.com/microsoft/onnxruntime/pull/17757).

The parameter we used in our cls_qnn.exe is **QuantizedData**: -116, 0.015875209f for input，and **DequantizedData**: -86, 0.08069417f for output.
The raw input preprocess is also using [mobilenetv2_helper.py](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/c_cxx/QNN_EP/mobilenetv2_classification/mobilenetv2_helper.py), and try to run the original onnx model and get the correct result.

If it's possible, may I have the kitten.jpg.raw you used? or it's the same to us?

**Comment by HectorSVC** [comment]
There are some changes recently. You need to use the latest main for both onnxruntime and the inference example code.

You can directly run the example code to get the kitten.jpg.raw.

The parameter is not just the QuantizedData and DequantizedData for input & output. All tensors inside the model are quantized.

By the way, any reason that you have to use the one converted by QNN tool chain?

**Comment by JohnnyWang19921007** [comment]
Got it, we will try the latest main for both onnxruntime and the inference example code.
By the way, the one in the last line you mean why we choose this model?

**Comment by HectorSVC** [comment]
You said this: When we try the sample "mobilenetv2_classification" with "Option 2: Use context binary generated by native QNN tool chain", the result is unexcepted.
Why you want to use the context binary generated by native QNN tool chain?

**Comment by HectorSVC** [comment]
Also, if you choose that option 2, you should run the command like:

REM run mobilenetv2-12_net_qnn_ctx.onnx (generated from native QNN) with QNN HTP backend
qnn_ep_sample.exe **--qnn** mobilenetv2-12_net_qnn_ctx.onnx kitten_input_**nhwc**.raw

**Comment by JohnnyWang19921007** [comment]
Hi @HectorSVC 
We have tried the latest main for both onnxruntime and the inference example code, and it works!
<img width="933" alt="image" src="https://github.com/microsoft/onnxruntime-inference-examples/assets/23184292/7cbd7f40-b417-4b4b-8e30-3fd08217eee0">

Thank you for the assistance, and we are moving to close this issue.
Happy new year!
